name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
        
    steps:
    - uses: actions/checkout@v2

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: "Static analyzer: Run"
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        enable: warning,style
        exclude_check: ./googletest
        std: c++20
        other_options: --library=qt.cfg,googletest.cfg
      working-directory: ./src
      

    - name: "Static analyzer: Publish report"
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'master'

    - name: Make project
      run: |
        cmake .
        cmake --build . --parallel 4
      working-directory: ./src

    - name: UT for BtsApplication
      run: make BtsApplicationUT 
      working-directory: ./src

    - name: Run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT
      working-directory: ./src

    - name: UT for COMMON
      run: make COMMON_UT
      working-directory: ./src

    - name: UT for UeApplication
      run: make UeApplicationUT
      working-directory: ./src

    # - name: Next Steps
    #   run: echo "Add your next steps here"

