name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: src
        
    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install cppcheck
      run: |
        sudo apt-get update && sudo apt-get install -y cppcheck

    - name: Run cppcheck
      run: |
        cppcheck --std=c++20 --enable=warning,style,performance --library=qt.cfg,googletest.cfg -igoogletest .

    - name: Run cmake
      run: |
        cmake .
      working-directory: ./src

    - name: Run C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CPP_LINTER_PR_REVIEW_SUMMARY_ONLY: true
      with:
        style: 'file'  # Use .clang-format config file
        tidy-checks: 'bugprone-*,performance-*,readability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-*'
        # only 'update' a single comment in a pull request thread.
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
        files-changed-only: true
        extra-args: '-std=c++20 -Wall -Wextra'
        version: 19
        verbosity: debug
        tidy-review: false
        ignore: 
          ".github|
           docs|
           lectures|
           src/bin|
           src/BTS|
           src/COMMON|
          !src/COMMON/Utils|
           src/googletest|
           src/lib
          "

    - name: Halt if linter found errors
      if: steps.linter.outputs.checks-failed > 0
      run: exit 1

    - name: Make project
      run: |
        cmake --build . --parallel 4
      working-directory: ./src

    - name: UT for BtsApplication
      run: make BtsApplicationUT 
      working-directory: ./src

    - name: Run BTS ut
      run: ./BTS/Tests/Application/BtsApplicationUT
      working-directory: ./src

    - name: UT for COMMON
      run: make COMMON_UT
      working-directory: ./src

    - name: UT for UeApplication
      run: make UeApplicationUT
      working-directory: ./src

    # - name: Next Steps
    #   run: echo "Add your next steps here"

